services:
  db:
    image: postgres:17-alpine
    container_name: pim_db
    environment:
      POSTGRES_DB: pim_db
      POSTGRES_USER: pim_user
      POSTGRES_PASSWORD: pim_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: pim_php
    command: >
        sh -c "
          echo '--- STARTING AUTO SETUP ---' &&
          git config --global --add safe.directory /var/www/html &&
          composer install &&
          chmod -R +x bin/ &&
          bin/console doctrine:database:create --if-not-exists &&
          bin/console doctrine:migrations:migrate --no-interaction &&
          bin/console doctrine:database:create --env=test --if-not-exists &&
          bin/console doctrine:migrations:migrate --env=test --no-interaction &&
          echo '--- SETUP FINISHED, STARTING PHP-FPM ---' &&
          php-fpm
        "
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: pim_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_data:
