<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260324102725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE price_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_price NUMERIC(10, 2) NOT NULL, new_price NUMERIC(10, 2) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C9CB8174584665A ON price_history (product_id)');
        $this->addSql('ALTER TABLE price_history ADD CONSTRAINT FK_4C9CB8174584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE price_history DROP CONSTRAINT FK_4C9CB8174584665A');
        $this->addSql('DROP TABLE price_history');
    }
}
